---
- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: purge default site
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /var/www/html
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  notify: restart nginx

- name: make configured site available
  copy:
    src: wordpress
    dest: /etc/nginx/sites-available/
  notify: restart nginx

- name: enable site
  file:
    state: link
    src: /etc/nginx/sites-available/wordpress
    dest: /etc/nginx/sites-enabled/wordpress
  ignore_errors: "{{ ansible_check_mode }}"
  notify: restart nginx

- name: configure php.ini
  lineinfile:
    dest=/etc/php/7.0/fpm/php.ini
    regexp="^[;\s]*{{ item.key }}"
    line="{{ item.key }} = {{ item.val }}"
  with_items: "{{ php_ini | default([]) }}"
  when: php_ini is defined
  notify: restart php-fpm

- name: configure php-fpm
  lineinfile:
    dest=/etc/php/7.0/fpm/php-fpm.conf
    regexp="^[;\s]*{{ item.key }}"
    line="{{ item.key }} = {{ item.val }}"
  with_items: "{{ php_fpm_conf | default([]) }}"
  when: php_fpm_conf is defined
  notify: restart php-fpm
